spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    use-legacy-processing: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true



github:
  api:
    url: https://api.github.com/
    token: "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"